soil_discover:
    resource: "@SoilDiscoverBundle/Resources/config/routing.yml"
    prefix:   /

soil_comment:
    resource: "@SoilCommentBundle/Resources/config/routing.yml"
    prefix:   /

soil_authority:
    resource: "@SoilAuthorityBundle/Resources/config/routing.yml"
    prefix:   /authority/

soil_user_track:
    resource: "@SoilUserTrackBundle/Resources/config/routing.yml"
    prefix:   /


