services:
    soil_comment.controller.cors_controller:
        class:     Soil\CommentBundle\Controller\CORSController

    soil_comment.controller.discover_controller:
        class:     Soil\CommentBundle\Controller\DiscoverController
        arguments: [@soil_disover.discoverer, @templating]

    soil_comment.controller.comment_controller:
        class: Soil\CommentBundle\Controller\CommentController
        arguments:
            - @soil_comment.service.comment
            - @soil_comment.service.entity
            - @soil_comment.service.author
        calls:
            - [setCorsController, [@soil_comment.controller.cors_controller]]
            - [setFormFactory, [@form.factory]]



    soil_comment.service.comment:
        class: Soil\CommentBundle\Service\CommentService
        arguments: [@doctrine_mongodb, @validator]
        calls:
            - [setEntityService, [@soil_comment.service.entity]]
            - [setAuthorService, [@soil_comment.service.author]]

    soil_comment.service.entity:
        class: Soil\CommentBundle\Service\EntityService
        arguments: [@doctrine_mongodb, @validator]

    soil_comment.service.author:
        class: Soil\CommentBundle\Service\AuthorService
        arguments: [@doctrine_mongodb, @validator, @soil_disover.discoverer]

    soil_comment.service.urinator:
        class: Soil\CommentBundle\Service\URInator
        arguments: [@router]

    soil_comment.form.comment_push:
            class: Soil\CommentBundle\Form\CommentPushForm
            tags:
                - { name: form.type, alias: CommentPush }



    soil_comment.controller.vote_controller:
        class: Soil\CommentBundle\Controller\VoteController
        arguments:
            - @soil_comment.service.comment
            - @soil_comment.service.entity
            - @soil_comment.service.author
        calls:
            - [setCorsController, [@soil_comment.controller.cors_controller]]